version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-druid-cdc"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_prefix = "dynamodb-druid-cdc"
disable_rollback = true
image_repositories = []
