name: Build

on: [push]

jobs:
  cljs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache project dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-clojure

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Prepare node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install node dependencies
        run: npm install

      - name: Run shadow-cljs server
        run: npm run server &

      - name: Wait for shadow-cljs server
        run: |
          timeout 45 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9630/api)" != "200" ]]; do sleep 5; done' || false

      - name: Run tests
        run: npm test

      - name: Create release bundle (unused at the moment)
        run: npm run build
