name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache project dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/shadow-cljs.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.2
        with:
          cli: 1.10.1.693
          lein: 2.9.1

      - name: Prepare node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install
      - run: npm test
      - run: ls ~/.m2

